Added support for --profile flag for docker-compose up and docker-com…
Silex/docker.el pull request #200
Opened 2022-05-21 06:47 UTC by HackTheOxidation

…pose down.

2022-05-21 11:22 UTC, Silex requested changes

2022-05-21 11:22 UTC, Silex commented on docker-compose.el
> +   ("p" "Profile" "--profile" read-string)
Needs a space after  `--profile`

2022-05-21 11:22 UTC, Silex commented on docker-compose.el
> +   ("p" "Profile" "--profile" read-string)
Same here

2022-05-21 11:24 UTC, Silex commented
Hello, please modify your commit with the requested changes, also change the commit message for `Support --profile flag for docker-compose up/down`

2022-05-21 12:44 UTC, HackTheOxidation commented on docker-compose.el
> +   ("p" "Profile" "--profile" read-string)
Good catch. Should be fixed now.

2022-05-22 10:28 UTC, merged

2022-05-22 10:28 UTC, Silex commented
Fantastic thanks! :+1: