feat: add V-term with environment and workdir set
Silex/docker.el pull request #222
Opened 2023-08-26 15:33 UTC by sfavazza

2023-08-30 10:04 UTC, sfavazza commented
@Silex can you have a look to this MR

2023-08-30 13:51 UTC, Silex requested changes
Thanks, please check my comments.

2023-08-30 13:51 UTC, Silex commented on docker-container.el
>    (if (fboundp 'vterm-other-window)
Please remove this formatting

2023-08-30 13:51 UTC, Silex commented on docker-container.el
Please remove extra space (between `env"` and `docker-container`).

2023-09-01 13:03 UTC, Silex approved these changes

2023-09-01 13:04 UTC, merged

2023-09-01 13:04 UTC, Silex commented
Thanks 👍

2023-09-01 13:18 UTC, Silex commented
Had to change from `aio-defun` to `defun` for it to work.

2023-09-04 09:45 UTC, sfavazza commented
I don't understand why it does not work for you with `aio-defun`, now that has been changed to `defun` I got this error:

````elisp
Debugger entered--Lisp error: (error "‘iter-yield’ used outside a generator")
  signal(error ("‘iter-yield’ used outside a generator"))
  error("`iter-yield' used outside a generator")
  iter-yield(#s(aio-promise nil nil))
  docker-container-vterm-env("odindevenv-tftp_srv-1")
  #f(compiled-function () (interactive nil) #<bytecode 0x164259ed9919ee3f>)()
  apply(#f(compiled-function () (interactive nil) #<bytecode 0x164259ed9919ee3f>) nil)
  #f(compiled-function (fn &rest args) #<bytecode 0xe55b325266e3da8>)(#f(compiled-function () (interactive nil) #<bytecode 0x164259ed9919ee3f>))
  apply(#f(compiled-function (fn &rest args) #<bytecode 0xe55b325266e3da8>) #f(compiled-function () (interactive nil) #<bytecode 0x164259ed9919ee3f>) nil)
  (lambda (fn &rest args) (interactive #f(compiled-function (spec) #<bytecode -0x10bbfb860b322f72>)) (apply '#f(compiled-function (fn &rest args) #<bytecode 0xe55b325266e3da8>) fn args))(#f(compiled-function () (interactive nil) #<bytecode 0x164259ed9919ee3f>))
  apply((lambda (fn &rest args) (interactive #f(compiled-function (spec) #<bytecode -0x10bbfb860b322f72>)) (apply '#f(compiled-function (fn &rest args) #<bytecode 0xe55b325266e3da8>) fn args)) #f(compiled-function () (interactive nil) #<bytecode 0x164259ed9919ee3f>) nil)
  docker-container-vterm-env-selection()
  funcall-interactively(docker-container-vterm-env-selection)
  call-interactively(docker-container-vterm-env-selection nil nil)
  command-execute(docker-container-vterm-env-selection)
```

This is due to the call to `aio-await` in the `docker-container-vterm-env`. It is the same approach like in the `docker-container-shell-env`. Can you please revert your change?

2023-09-06 19:18 UTC, Silex commented
Hum, right I should have also replaced the `aio-await` with a sync version.

Anyway I reverted my change, but please help me debug this then: https://github.com/Silex/docker.el/actions/runs/6101476986

2023-09-07 18:27 UTC, Silex commented
@sfavazza

2023-09-07 21:46 UTC, sfavazza commented
I don't understand why the `vterm-other-window` function is not found. The fboundp test is performed also in the `docker-container-vterm` but it does not give any problem. I am investigating, but it does not seems trivial. Do you have any idea whether the `aio` macros may have an impact on the loading order?

![image](https://github.com/Silex/docker.el/assets/36377461/80e97770-0566-4bef-8c92-f98a12f4c77b)

2023-09-09 00:00 UTC, Silex commented
@LaurenceWarne: I summon you here because you might have an idea why we have these errors.

https://github.com/skeeto/emacs-aio is a bit special so there is maybe something we are missing.

2023-09-09 14:40 UTC, LaurenceWarne commented
Experimentally, the `fboundp` call appears to have to directly precede the statement.  It would be interesting to know more about it, though I can't appear to find any doc?

Opened a PR anyway: https://github.com/Silex/docker.el/pull/223.

2023-09-09 15:51 UTC, sfavazza commented
@LaurenceWarne much appreciated your intervention